/* BANCO DE DADOS - data_science */

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */

/* QUAL O MAXIMO E MINIMO E AMPLITUDE DE CADA MAQUINA  */

SELECT MAQUINA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
(MAX(QTD) - MIN(QTD)) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;

/* ACRESCENTE A MEDIA AO RELATORIO */

SELECT MAQUINA,
ROUND(AVG(QTD),2) AS MEDIA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
(MAX(QTD) - MIN(QTD)) AS AMPLITUDE
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 4 DESC;
