/* BANCO DE DADOS - data_science */

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */

/* VARIANCIA E DESVIO-PADRAO */

-- FUNÇÕES DE CALCULO DA VARIANCIA E DO DESVIO-PADRAO
VAR_POP(coluna)	-- CALCULA A VARIANCIA
STDDEV_POP(coluna) -- CALCULA O DESVIO-PADRAO

SELECT
MAQUINA,
ROUND(AVG(QTD),2) AS MEDIA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
(MAX(QTD) - MIN(QTD)) AS AMPLITUDE,
ROUND(VAR_POP(QTD),2) AS VARIANCIA,
ROUND(STDDEV_POP(QTD),2) AS DESV_PAD
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 5 DESC;