/* BANCO DE DADOS - data_science */

/*CONTINUAÇÃO DO SCRIPT:
01_03-Modelagem_DB_X_Modelagem_Data_Science-Importacao_dados.sql
*/

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */
/* MODA */

-- VERIFICANDO DADOS IMPORTADOS
SELECT * FROM MAQUINAS;

/*QUAL A MÉDIA DE CADA MAQUINA */

SELECT
MAQUINA,
AVG(QTD) AS MEDIA_QTD -- AVG() CALCULA A MÉDIA
FROM MAQUINAS
GROUP BY MAQUINA 
-- AGRUPA EM TORNO DAS MAQUINAS PARA ACHAR A MEDIA DE CADA MAQUINA
ORDER BY 2 DESC; -- PROJETA PELA MAIOR MEDIA ENCONTRADA

/* ARREDONDANDO */

-- SINTAXE, EXEMPLO:
-- ROUND(nome_da_coluna, numero_de_casas_decimais)
-- ROUND(COLUNA,2)

SELECT
MAQUINA,
ROUND(AVG(QTD),2) AS MEDIA_QTD -- ARREDONDA O VALOR DAS MEDIAS
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

/* QUAL A MODA DAS QUANTIDADES */
-- MODA = FREQUENCIA(S) DE MAIOR INCIDÊNCIA
-- A VARIAVEL PODE TER MAIS DE UMA MODA (MULTIMODAL)

SELECT
MAQUINA,
QTD,
COUNT(*) AS MODA -- CONTA AS FREQUENCIAS IGUAIS, IGUAL A MODA
FROM MAQUINAS
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC; -- PROJETA AS MAIORES MODAS PRIMEIRO


/* QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA */

SELECT
MAQUINA,
QTD,
COUNT(*)
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01' -- USO DE FILTRO PARA RETORNA OS VALORES DA VARIAVEL ESCOLHIDA
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1; -- RETORNA APENAS A PRIMEIRA MAIOR MODA ENCONTRADA, PODEM HAVER MAIS CUIDADO!!! 
-- RETORNA A PRIMEIRA MAIOR MODA APENAS DA 'Maquina 01'

SELECT
MAQUINA, 
QTD, 
COUNT(*)
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT 
MAQUINA, 
QTD, 
COUNT(*)
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

/* MODA DO DATASET INTEIRO */

SELECT
QTD, 
COUNT(*) AS MODA -- MODA = CONTAR VALORES REPETIDOS
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;
-- RETORNA A MODA DO DATASET, SEM SE PREOCUPAR COM A MAQUINA