/* BANCO DE DADOS - data_science */

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */

/* VARIANCIA E DESVIO-PADRAO */

/* FUNÇÕES DE CALCULO DA VARIANCIA E DO DESVIO-PADRAO */
-- DE UMA POPULACAO
VAR_POP(coluna)	-- CALCULA A VARIANCIA DE UMA POPULACAO
STDDEV_POP(coluna) -- CALCULA O DESVIO-PADRAO DE UMA POPULACAO
-- DE UMA AMOSTRA
VARIANCE(coluna) -- CALCULA A VARIANCIA DE UMA AMOSTRA
STDDEV(coluna) -- CALCULA O DESVIO-PADRAO DE UMA AMOSTRA

SELECT
MAQUINA,
ROUND(AVG(QTD),2) AS MEDIA,
MAX(QTD) AS MAXIMO,
MIN(QTD) AS MINIMO,
(MAX(QTD) - MIN(QTD)) AS AMPLITUDE,
ROUND(VAR_POP(QTD),2) AS VARIANCIA_POP, -- VARIANCIA DA POPULACAO
ROUND(VARIANCE(QTD),2) AS VARIANCIA_AMOST, -- VARIANCIA DA AMOSTRA
ROUND(STDDEV_POP(QTD),2) AS DESV_PAD_POP, -- DESVIO-PADRAO DA POPULACAO
ROUND(STDDEV(QTD),2) AS DESV_PAD_AMOST -- DESVIO-PADRAO DA AMOSTRA
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 5 DESC;