/* BANCO DE DADOS - data_science */

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */

/* MEDIANA */

-- NAO EXISTE FUNCAO PARA MEDIANA
-- POR ISSO NECESSARIO CRIAR

-- CRIANDO FUNCAO MEDIAN
CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
   RETURNS NUMERIC AS
$$ -- BLOCO DE PROGRAMACAO, ALTERA DELIMITADOR ATE ACHAR ELE NOVAMENTE
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$ -- FIM DO BLOCO
LANGUAGE 'sql' IMMUTABLE; -- DEFINE A LINGUAGEM NO BLOCO DE PROGRAMACAO
					 
CREATE AGGREGATE median(NUMERIC) (
  SFUNC=array_append,
  STYPE=NUMERIC[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);

-- VERIFICANDO A NOVA FUNCAO QUE CALCULA A MEDIANA, MEDIAN()
SELECT
ROUND(MEDIAN(QTD),2) AS MEDIANA
FROM MAQUINAS;

-- VERIFICANDO AS MEDIANAS
SELECT
ROUND(MEDIAN(QTD),2) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01';
								
SELECT
ROUND(MEDIAN(QTD),2) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02';

SELECT
ROUND(MEDIAN(QTD),2) AS MEDIANA
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03';

-- INSERINDO NOVOS VALORES PARA ALTERAR A MEDIANA
INSERT INTO MAQUINAS VALUES('Maquina 01',11,15.9);
INSERT INTO MAQUINAS VALUES('Maquina 02',11,15.4);
INSERT INTO MAQUINAS VALUES('Maquina 03',11,15.7);
INSERT INTO MAQUINAS VALUES('Maquina 01',12,30);
INSERT INTO MAQUINAS VALUES('Maquina 02',12,24);
INSERT INTO MAQUINAS VALUES('Maquina 03',12,45);

-- VERIFICANDO AS ALTERACOES E FUNCAO MEDIANA
SELECT
MAQUINA,
ROUND(MEDIAN(QTD),2) AS MEDIANA
FROM MAQUINAS
GROUP BY 1
ORDER BY 2;

-- DELETANDO OS NOVOS VALORES
DELETE FROM MAQUINAS
WHERE DIA = 11 OR DIA = 12;