/* BANCO DE DADOS - data_science */

/* ESTATÍSTICA BÁSICA COM BANCO DE DADOS */

/* MODA - FUNCAO ALTERNATIVA */

-- MODE() WITHIN GROUP(ORDER BY COLUNA)

-- VERIFICANDO DADOS
SELECT * FROM MAQUINAS;

-- SELECT DA MODA TOTAL
SELECT
MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA"
FROM MAQUINAS;

-- SELECT DA MODA SEPARANDO POR MAQUINA
SELECT
MAQUINA,
MODE() WITHIN GROUP(ORDER BY QTD) AS "MODA" 
FROM MAQUINAS
GROUP BY MAQUINA;