-- DATABASE: DATA_SCIENCE
-- TABLE: FUNCIONARIOS

/* VARIAVEIS DUMMY PARA MACHINE LEARNING */

-- VERIFICANDO NOME, CARGO E SEXO DOS FUNCIONARIOS
-- PRINCIPAIS DADOS HÁ UTILIZAR AO LONGO PROGRAMA
SELECT
NOME,
CARGO,
SEXO 
FROM FUNCIONARIOS;

/* 1 - CASE */
-- "CASE" SÃO OS CASOS 

-- VERIFICANDO CARGO
SELECT NOME, CARGO FROM FUNCIONARIOS;

-- CASE (WHEN, THEN, ELSE)
-- WHEN = QUANDO
-- THEN = ENTÃO
-- ELSE = SENÃO
SELECT
NOME,
CARGO,
CASE
	WHEN CARGO = 'Financial Advisor' THEN 'Condicao 01'
	WHEN CARGO = 'Structural Engineer' THEN 'Condicao 02'
	WHEN CARGO = 'Recruiting Manager' THEN 'Condicao 03'
	WHEN CARGO = 'Software Engineer III' THEN 'Condicao 04'
	ELSE 'Outras condicoes'
END AS "CONDICOES"
FROM FUNCIONARIOS;
-- NÃO USA ',' AO FINAL DO WHEN, POIS NÃO É UMA COLUNA

-- SIMPLIFICANDO SEXO PARA MACHINE LEARNING
-- USO DO CASE
SELECT
NOME,
CASE
	WHEN SEXO = 'Masculino' THEN 'M'
	ELSE 'F'
END AS "SEXO"
FROM FUNCIONARIOS;

/* 2 - UTILIZANDO VALORES BOOLEANOS */

-- PROJEÇÃO EM BOOLEANO
SELECT
NOME,
CARGO,
(SEXO = 'Masculino') AS MASCULINO, -- TRUE OU FALSE (COLUNA EM BOOLEANOS)
(SEXO = 'Feminino') AS FEMININO 
FROM FUNCIONARIOS;
-- EXPRESSÕES DE COMPARAÇÃO ENTRE PARENTES GERAM RESULTADOS BOOLEANO,
-- "TRUE" OU "FASE"

/* 3 - MESCLANDO TÉCNICAS (CASE, BOOLEANO) PARA FORMAR COLUNA DUMMY (VARIÁVEL DUMMY)*/
/* DUMMY SÃO COLUNAS BOOLEANAS */

-- SIMPLIFICANDO COLUNA "SEXO" PARA MACHINE LEARNING
-- TRANSFORMANDO COLUNA EM DUAS COLUNAS BOOLEANAS (COLUNAS DUMMY)
-- USO DO CASE
SELECT
NOME,
CARGO,
SEXO,
CASE
	WHEN SEXO = 'Masculino' THEN 'M'
	ELSE 'F'
END AS SEXO_SIMPLIFICADO,
-- COLUNAS DUMMY (BOOLEANOS)
CASE
	WHEN (SEXO = 'Masculino') = TRUE THEN 1
	ELSE 0
END AS MASCULINO,
CASE
	WHEN (SEXO = 'Feminino') = TRUE THEN 1
	ELSE 0
END AS FEMINIO
FROM FUNCIONARIOS;
-- "CASE" ATE "END" REPRESENTA UMA COLUNA, LOGO SE NECESSARIO, COLOCAR "," AO FINAL.