/* VARIAVEIS DUMMY PARA MACHINE LEARNING */

/* UTILIZANDO CASE */

-- PROJETANDO NOME E SEXO DOS FUNCIONARIOS
SELECT
NOME,
SEXO 
FROM FUNCIONARIOS;

/* CASE */

-- VERIFICANDO CARGO
SELECT NOME, CARGO FROM FUNCIONARIOS;

-- CASE (WHEN, THEN, ELSE)
SELECT
NOME,
CARGO,
CASE
	WHEN CARGO = 'Financial Advisor' THEN 'Condicao 01'
	WHEN CARGO = 'Structural Engineer' THEN 'Condicao 02'
	WHEN CARGO = 'Recruiting Manager' THEN 'Condicao 03'
	WHEN CARGO = 'Software Engineer III' THEN 'Condicao 04'
	ELSE 'Outras condicoes'
END AS "CONDICOES"
FROM FUNCIONARIOS;
-- NÃO USA ',' AO FINAL DO WHEN, POIS NÃO É UMA COLUNA

-- SIMPLIFICANDO SEXO PARA MACHINE LEARNING
-- USO DO CASE
SELECT
NOME,
CASE
	WHEN SEXO = 'Masculino' THEN 'M'
	ELSE 'F'
END AS "SEXO"
FROM FUNCIONARIOS;

/* UTILIZANDO VALORES BOOLEANOS */

-- PROJEÇÃO EM BOOLEANO
SELECT
NOME,
CARGO,
(SEXO = 'Masculino') AS MASCULINO, -- TRUE OU FALSE (COLUNA EM BOOLEANOS)
(SEXO = 'Feminino') AS FEMININO 
FROM FUNCIONARIOS;

/* MESCLANDO TÉCNICAS (CASE, BOOLEANO) PARA FORMAR COLUNA DUMMY */
/* DUMMY SÃO COLUNAS BOOLEANAS */

-- SIMPLIFICANDO SEXO PARA MACHINE LEARNING
-- MAIS PROXIMO DE BOOLEANOS
-- USO DO CASE
SELECT
NOME,
CARGO,
SEXO,
-- COLUNAS DUMMY (BOOLEANOS)
CASE
	WHEN (SEXO = 'Masculino') = TRUE THEN 1
	ELSE 0
END AS MASCULINO,
CASE
	WHEN (SEXO = 'Feminino') = TRUE THEN 1
	ELSE 0
END AS FEMINIO
FROM FUNCIONARIOS;