-- DATABASE: data_science
-- TABLE: funcionarios

/* CASE E IF */

-- Verificando tabela a ser trabalhada
SELECT * FROM FUNCIONARIOS;

/* CASE */
-- USADO NORMALMENTE PARA PROJEÇÃO (SELECT)

SELECT
IDFUNCIONARIO,
CASE
	WHEN (SEXO = 'Masculino') THEN 'M'
	ELSE 'F'
END AS SEXO,
CASE
	WHEN (SEXO = 'Masculino') THEN 1
	ELSE 0
END AS MASCULINO,
CASE
	WHEN (SEXO = 'Feminino') THEN 1
	ELSE 0
END AS FEMININO,
NOME
FROM FUNCIONARIOS;

/* IF */
-- USADO NORMALMENTE PARA BLOCOS DE PROGRAMAÇÃO TCL

DO
$$
BEGIN
IF EXISTS (SELECT NOME FROM FUNCIONARIOS WHERE NOME = 'Juan') THEN
	RAISE NOTICE 'Existe Juan';
ELSIF EXISTS (SELECT NOME FROM FUNCIONARIOS WHERE NOME = 'Armstrong') THEN
	RAISE NOTICE 'Existe Armstrong';
ELSE
	RAISE NOTICE 'Não existe este funcionario';
END IF;
END
$$