-- DATABASE: data_science
-- TABLE: funcionarios

/* CASE E IF */

-- Verificando tabela a ser trabalhada
SELECT * FROM FUNCIONARIOS;

/* CASE */
-- USADO NORMALMENTE PARA PROJEÇÃO (SELECT)

SELECT
IDFUNCIONARIO,
CASE
	WHEN (SEXO = 'Masculino') THEN 'M'
	ELSE 'F'
END AS SEXO,
CASE
	WHEN (SEXO = 'Masculino') THEN 1
	ELSE 0
END AS MASCULINO,
CASE
	WHEN (SEXO = 'Feminino') THEN 1
	ELSE 0
END AS FEMININO,
NOME
FROM FUNCIONARIOS;

/* IF */
-- USADO NORMALMENTE PARA BLOCOS DE PROGRAMAÇÃO TCL

DO
$$ -- MUDA O DELIMITADOR
BEGIN -- COMEÇA UMA TRANSAÇÃO
IF EXISTS (SELECT NOME FROM FUNCIONARIOS WHERE NOME = 'Juan') THEN -- SUBQUERY DENTRO DO IF
	RAISE NOTICE 'Existe Juan'; -- IMPREME NA TELA A MENSAGEM
ELSIF EXISTS (SELECT NOME FROM FUNCIONARIOS WHERE NOME = 'Armstrong') THEN -- SUBQUERY DENTRO DO ELSIF
	RAISE NOTICE 'Existe Armstrong'; -- IMPREME NA TELA A MENSAGEM
ELSE -- PARA TODOS OS OUTROS CASOS (EXCEÇÃO)
	RAISE NOTICE 'Não existe este funcionario'; -- IMPREME NA TELA A MENSAGEM
END IF;
END -- TERMINA A TRANSAÇÃO
$$ -- VOLTA COM O DELIMITADOR AO NORMAL