-- DATABASE: data_science
-- TABLE: funcionarios

-- Verificar tabela que será utilizada
SELECT * FROM FUNCIONARIOS;

/* Loops */
-- LOOP
-- WHILE
-- FOR
-- FOREACH

/* LOOP */
-- IF EXIT
-- EXIT WHEN
-- IF CONTINUE
-- CONTINUE WHEN

-- IF EXIT
CREATE PROCEDURE contador_loop_if_exit()
LANGUAGE plpgsql
AS
$$
DECLARE CONTADOR INTEGER = 0;
BEGIN
	LOOP
		IF CONTADOR > 5 THEN
			EXIT;
		END IF;
		RAISE NOTICE 'CONTADOR É %', CONTADOR;
		CONTADOR = CONTADOR + 1;
	END LOOP;
END;
$$

CALL contador_loop_if_exit();

DROP PROCEDURE contador_loop_if_exit();

-- Ou, sem criar uma função (PROCEDURE)
-- 'DO' executa um bloco de função anomina
DO
$$
DECLARE CONTADOR INTEGER = 0;
BEGIN
	LOOP
		IF CONTADOR > 5 THEN
			EXIT;
		END IF;
		RAISE NOTICE 'CONTADOR É %', CONTADOR;
		CONTADOR = CONTADOR + 1;
	END LOOP;
END;
$$

-- EXIT WHEN
CREATE PROCEDURE contador_loop_exit_when()
LANGUAGE plpgsql
AS
$$
DECLARE counter INTEGER=0;
BEGIN
	LOOP
		EXIT WHEN counter = 5;
		counter = counter + 1;
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

CALL contador_loop_exit_when();

DROP PROCEDURE contador_loop_exit_when();

-- CONTINUE (IF CONTINUE)
-- PULA PARA A PROXIMA ITERAÇÃO
DO
$$
DECLARE CONTADOR INTEGER = 0;
BEGIN
	LOOP
		CONTADOR = CONTADOR + 1;
		IF (CONTADOR = 5) THEN
			CONTINUE;
		END IF;
		IF (CONTADOR > 10) THEN
			EXIT;
		END IF;
		RAISE NOTICE 'CONTADOR = %', CONTADOR;
	END LOOP;
END;
$$


-- CONTINUE WHEN
-- DEFINE UMA EXPRESSÃO, QUANDO CUMPRIDA DESENCADEIA O CONTINUE
-- OU SEJA, PULA PARA A PROXIMA ITERAÇÃO
DO
$$
DECLARE CONTADOR INTEGER = 0;
BEGIN
	LOOP
		CONTADOR = CONTADOR + 1;
		CONTINUE WHEN (CONTADOR = 5);
		EXIT WHEN (CONTADOR > 10);
		RAISE NOTICE 'CONTADOR = %', CONTADOR;
	END LOOP;
END;
$$

/* WHILE */

CREATE PROCEDURE contador_while()
LANGUAGE plpgsql
AS
$$
DECLARE counter INTEGER=0;
BEGIN
	WHILE (counter < 5) LOOP -- LAÇO ENQUANTO A EXPRESSÃO FOR VERDADEIRA
		counter = counter + 1;
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

CALL contador_while();

DROP PROCEDURE contador_while;

/* FOR */
-- PERCORRE LISTA E ARRAY
-- FOR IN QUERY, PERCORRE QUERY, LINHA POR LINHA

-- LAÇO QUE PECORRE UMA LISTA PRÉDETERMINADA
CREATE PROCEDURE contador_for()
LANGUAGE plpgsql
AS
$$
BEGIN
	FOR counter IN 1..10 LOOP
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

CALL contador_for();

DROP PROCEDURE contador_for;
-- NÃO PRECISA DECLARAR A VARIAVEL CONTADOR
-- NO FOR, A VARIAVEL CONTADOR É CRIADA E POR DEFAULT RECEBE O TIPO 'INTEGER' (INTEIRO)

-- ou, sem criar uma função
DO
$$
BEGIN
	FOR counter IN 1..10 LOOP -- PERCORRE A LISTA, SOMANDO 1 A VARIAVEL COUNTER A CADA ITERAÇÃO
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

-- REVERSE
-- SUBTRAI VALOR DA VARIAVEL CONTADOR A CADA ITERAÇÃO
DO
$$
BEGIN
	FOR counter IN REVERSE 10..1 LOOP -- PERCORRE A LISTA, SUBTRAINDO 1 A VARIAVEL COUNTER A CADA ITERAÇÃO
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

-- BY 2
DO
$$
BEGIN
	FOR counter IN REVERSE 10..1 BY 2 LOOP -- PERCORRE A LISTA DE 2 EM 2 (BY 2)
		RAISE NOTICE 'Counter %', counter;
	END LOOP;
END;
$$

-- FOR IN QUERY
-- PERCORRE UMA DETERMINA CONSULTA
DO
$$
DECLARE
	FUNC VARCHAR(30);
	CONTADOR INTEGER = 0;
BEGIN
	FOR CONTADOR, FUNC IN
		SELECT
		IDFUNCIONARIO,
		NOME
		FROM FUNCIONARIOS
	LOOP
		RAISE NOTICE 'O nome do funcionario é %, seu ID é %', FUNC, CONTADOR;
	END LOOP;
END;
$$
-- ITERA LINHA POR LINHA DA CONSULTA (QUERY)
-- SALVA, A CADA ITERAÇÃO, A VALOR DO REGISTRO/LINHA NA VARIAVEL

-- QUANDO USADO MAIS DE UMA VARIAVEL,
-- OS VALORES DAS COLUNAS SÃO SALVOS NAS VARIAVEIS,
-- NA ORDEM EM QUE AS COLUNAS SÃO NOMEADAS NA QUERY DO FOR

-- A QUERY DO FOR NÃO É FINALIZADA COM DELIMITADOR ";"

/* FOREACH */

-- EM VEZ DE ITERAR PELAS LINHAS RETORNADAS POR UMA CONSULTA SQL,
-- ELE ITERA PELOS ELEMENTOS DE UM VETOR (ARRAY)

-- ARRAY - VETOR
DO
$$
DECLARE
	VEC INTEGER[] = '{1,2,3,4,5,6}';
	i INTEGER;
BEGIN
	FOREACH i IN ARRAY VEC LOOP
		RAISE NOTICE 'Iteracao %',i; 
	END LOOP;
END;
$$
-- É NECESSÁRIO DEFINIR NO LAÇO (FOREACH) A VARIAVEL ARRAY, COMO UM ARRAY.

-- ARRAY - MATRIZ
DO
$$
DECLARE
	Key_Val VARCHAR(4)[] = '{{"Key1","Val1"},{"Key2","Val2"}}'; -- ARRAY, POREM MATRIZ
	Mensagem VARCHAR(4)[]; -- VARIAVEL CONTADOR, SENDO UM ARRAY PARA GUARDAR MAIS DE UM VALOR POR ITERAÇÃO
BEGIN
	FOREACH Mensagem SLICE 1 IN ARRAY Key_Val LOOP
		RAISE NOTICE 'Key is % and value is %',Mensagem[1], Mensagem[2];
	END LOOP;
END;
$$
-- 'SLICE' AJUDA NO CASO DE UMA MATRIZ.
-- SLICE 0, OU OMITIDO, ITERA A PARTIR DE CADA ELEMENTO INDIVIDUAL DE UM ARRAY
-- SLICE POSITIVO, ITERA A PARTIR DO NUMERO DE REGISTROS ESPECIFICADOS PELO SLICE
-- NESSES CASOS A VARIAVEL CONTADOR DEVE SER UM ARRAY PARA SUPORTAR RECEBER (GUARDAR) MAIS DE UMA VALOR POR ITERAÇÃO