/* ARRAY - VETOR */

/* SINTAXE POSTGRESQL:
nome_coluna tipo [] -- NÃO PRECISA ESPECIFICAR O TAMANHO DO ARRAY
*/

/* SINTAXE ANSI SQL - SUPORTADO PELO POSTGRESQL:
nome_coluna tipo ARRAY [tamanho] -- INDICAR O TAMANHO DO ARRAY
ou
nome_coluna tipo ARRAY  -- SEM ESPECIFICAR O TAMANHO DO ARRAY
*/

/* EXEMPLO */
CREATE TABLE ESCALA_TRABALHO (
IDFUNC INT,
ESCALA CHAR(3)[] -- ARRAY
);

-- INSERINDO REGISTROS
INSERT INTO ESCALA_TRABALHO(IDFUNC, ESCALA) VALUES
(1,'{"SEG","TER","QUA"}'),
(2,'{"QUI","SEX","SAB"}'),
(3,'{"SEG","QUA","SEX"}');

-- VERIFICANDO TABELA
SELECT * FROM ESCALA_TRABALHO

/* CONSULTAS - QUERYS */
/* 1 - ESCALA DE TRABALHO DO FUNCIONÁRIO 2? */
SELECT 
IDFUNC,
ESCALA
FROM ESCALA_TRABALHO
WHERE IDFUNC = 2;

/* 2 - QUAL PRIMEIRO DIA DA SEMANA QUE CADA FUNCIONÁRIO COMEÇA A TRABALHAR? */
SELECT
IDFUNC,
ESCALA[1]
FROM ESCALA_TRABALHO;
-- A POSIÇÃO DO ARRAY NO POSTGRESQL COMEÇA A CONTAR DO 1, NÃO DO 0

/* 3 - QUAIS FUNCIONÁRIOS TRABALHAM ÁS QUARTA-FEIRA? */
SELECT
IDFUNC
FROM ESCALA_TRABALHO
WHERE 'QUA' = ANY(ESCALA);
-- ANY = EM QUALQUER POSIÇÃO
-- NESSE CASO: "EM QUALQUER POSIÇÃO DA COLUNA ESCALA"

/* ALTERAR ESCALA DE TRABALHO DO FUNCIONÁRIO 3 - TER, QUI E SAB */
-- VERIFICANDO TABELA ANTES DA ALTERAÇÃO
SELECT * FROM ESCALA_TRABALHO;

-- ALTERAÇÃO
UPDATE ESCALA_TRABALHO
SET ESCALA = ARRAY['TER','QUI','SAB']
WHERE IDFUNC = 3;
-- ARRAY É ASPAS SIMPLES

-- VERIFICANDO TABELA DEPOIS DA ALTERAÇÃO
SELECT * FROM ESCALA_TRABALHO;