/* BANCO DE DADOS: data_science */
/* TABELA: funcionarios */

-- VERIFICANDO TABELA
SELECT * FROM FUNCIONARIOS;

/* MULTIPLOS CONTADORES */
-- CONTAR DIFERENTES COISAS EM UMA UNICA PESQUISA(QUERY).
-- DUAS FORMAS DE FAZER ESSE TIPO DE PESQUISA É ATRAVES DE "SUBQUERY" E "COUNT-FILTER".

/*
SUMARIO:
1 - SUBQUERY
2 - COUNT-FILTER
*/

/* 1 - SUBQUERY */

-- COUNT(*)
-- PESQUISAR NÚMERO DE FUNCIONARIOS
SELECT
COUNT(*) AS "QTD TOTAL"
FROM FUNCIONARIOS;

-- PESQUISAR NÚMERO DE FUNCIONARIOS E O NÚMERO DE FUNCIONARIOS MASCULINOS
SELECT
COUNT(*) AS "QTD TOTAL",
COUNT('Masculino') AS "Masculinos"
FROM FUNCIONARIOS;
-- PESQUISA RODA POREM COM ERRO!
-- NÃO SÃO 1000 FUNCIONARIOS MASCULINOS.

SELECT
SEXO,
COUNT(*) AS "Masculino"
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO;
-- A CONSULTA TEM O RETORNO CORRETO, POREM EM DUAS COLUNAS.
-- NÚMERO DE FUNCIONARIOS MASCULINOS = 504.
-- QUEREMOS EM 1 COLUNA, A INFORMAÇÃO DOS FUNCIONARIOS DO SEXO MASCULINO.

SELECT
COUNT(*) AS "QTD_TOTAL",
COUNT(SELECT
SEXO,
COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS "Masculino"
FROM FUNCIONARIOS;
-- ERRO DE SINTAXE DA FUNÇÃO 'COUNT', MAS ESTAMOS NO CAMINHO CERTO.

SELECT
COUNT(*) AS "QTD_TOTAL",
(SELECT
SEXO,
COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS "Masculino"
FROM FUNCIONARIOS;
-- ERRO, POIS SUBQUERY SÓ RETORNA UMA COLUNA.

SELECT
COUNT(*) AS "QTD_TOTAL",
(SELECT
COUNT(*)
FROM FUNCIONARIOS
WHERE SEXO = 'Masculino'
GROUP BY SEXO) AS "Masculino"
FROM FUNCIONARIOS;
-- RETORNA O VALOR ESPERADO.
-- SUBQUERY É UMA NOVA CONSULTA(QUERY) ENTRE PARÊNTESES,
-- ONDE SÓ RETORNA UMA COLUNA.
-- DENTRO DA SUBQUERY NÃO TEM DELIMITADOR.

/* 2 - COUNT-FILTER */
-- FILTER SÓ FUNCIONA COM COUNT!!!

SELECT
COUNT(*) AS "QTD_TOTAL",
COUNT(*) FILTER(WHERE SEXO = 'Masculino') AS "MASCULINO"
FROM FUNCIONARIOS;
-- "FILTER" ADICIONA UM FILTRO AO CONTADOR "COUNT".
-- MELHORA A PERFORMANCE DA CONSULTA EM RELAÇÃO A SUBQUERY.

SELECT
COUNT(*) AS "QTD_TOTAL",
COUNT(*) FILTER(WHERE SEXO = 'Masculino') AS "MASCULINO",
COUNT(*) FILTER(WHERE DEPARTAMENTO = 'Books') AS "BOOKS"
FROM FUNCIONARIOS;
-- FÁCIL DE FAZER MULTIPLOS FILTROS DE CONTADOR.

SELECT
COUNT(*) AS "QTD_TOTAL",
COUNT(*) FILTER(WHERE SEXO = 'Masculino') AS "MASCULINO",
COUNT(*) FILTER(WHERE DEPARTAMENTO = 'Books') AS "BOOKS",
COUNT(*) FILTER(WHERE SALARIO > 140000) AS "SALARIO_140K"
FROM FUNCIONARIOS;
-- MISTURANDO FILTROS DIFERENTES: STRINGS E NUMERICOS.