/* BANCO DE DADOS: data_science */
/* TABELA: funcionarios */

-- VERIFICANDO TABELA
SELECT * FROM FUNCIONARIOS;

/* REFORMATAÇÃO DE STRINGS */
-- FUNÇÕES DE STRINGS SUMÁRIO:
-- DISTINCT - REMOVE REDUNDANCIAS
-- UPPER - CAIXA ALTA
-- LOWER - CAIXA BAIXA
-- CONCATENANDO STRINGS
-- TRIM - REMOVER ESPAÇOS
-- LENGTH - CONTANDO CARACTERES

/* DISTINCT */
-- LISTAR TODOS OS ELEMENTOS DE UMA COLUNA
SELECT
DEPARTAMENTO
FROM FUNCIONARIOS;

-- LISTAR TODOS OS ELEMENTOS DE UMA COLUNA SEM REPETIÇÃO
-- FUNÇÃO "DISTINCT"
SELECT
DISTINCT DEPARTAMENTO
FROM FUNCIONARIOS;

/* UPPER - CASE */
-- COLOCAR TODAS AS STRINGS DE UMA COLUNA EM LETRAS MAIÚSCULAS
SELECT
DISTINCT UPPER(DEPARTAMENTO)
FROM FUNCIONARIOS;

/* LOWER - CASE */
-- COLOCAR TODAS AS STRINGS DE UMA COLUNA EM LETRAS MINUSCULAS
SELECT
DISTINCT LOWER(DEPARTAMENTO)
FROM FUNCIONARIOS;

/* CONCATENANDO STRINGS */
-- CONCATENAR COLUNAS E/OU STRINGS
-- CONCATENA COM PIPE DUPLO ("||")
SELECT
CARGO || ' - ' || DEPARTAMENTO AS "CARGO COMPLETO"
FROM FUNCIONARIOS;

-- USANDO VARIAS FUNÇÕES DE STRING EM CONJUNTO COM A CONCATENAÇÃO
SELECT
DISTINCT UPPER(CARGO || ' - ' || DEPARTAMENTO) AS "CARGO COMPLETO"
FROM FUNCIONARIOS;

/* TRIM - REMOVER ESPAÇOS */

SELECT '     OI';
SELECT TRIM('     OI');

/* LENGTH - CONTANDO CARACTERES*/
SELECT LENGTH('     OI');

-- USANDO TRIM E LENGTH EM CONJUNTO
SELECT LENGTH(TRIM(('     OI')));
-- REMOVEU OS ESPAÇOS EM BRANCO
-- E A FUNÇÃO LENGTH CONFIRMOU SERVIU PARA CONFIRMAR

/* DESAFIO - CRIAR UMA COLUNA AO LADO DA COLUNA CARGO, QUE DIGA SE A PESSOA É ASSISTENTE OU NÃO. */

-- PRIMEIRA SOLUÇÃO
SELECT
NOME,
CARGO,
(CARGO LIKE '%Assistant%') AS "ASSISTANT?"
FROM FUNCIONARIOS;

-- SEGUNDA SOLUÇÃO
SELECT
NOME,
CARGO,
CASE WHEN (CARGO LIKE '%Assistant%') = 'true'
	THEN 1
	ELSE 0
	END AS "ASSISTANT?"
FROM FUNCIONARIOS;