-- DESCOBRIR QUAL É A CONFIGURAÇÃO DE DATA (DATE)
SHOW datestyle;

-- DESCOBRIR QUAL É A VERSÃO DO PostgreSQL EM USO
SELECT VERSION();

-- DESCOBRIR QUAL É A VERSÃO DO PostgreSQL EM USO DE FORMA RESUMIDA
SHOW SERVER_VERSION;