-- DESCOBRIR QUAL É A CONFIGURAÇÃO DE DATA (DATE)
SHOW datestyle;

-- DESCOBRIR QUAL É A VERSÃO DO PostgreSQL EM USO
SELECT VERSION();

-- DESCOBRIR QUAL É A VERSÃO DO PostgreSQL EM USO DE FORMA RESUMIDA
SHOW SERVER_VERSION;

-- CHECK USUARIO ATUAL
SELECT CURRENT_USER;

-- CHECK TO USERS
SELECT USENAME FROM PG_USER;

/* AUTO INCREMENTAÇÃO NO POSTGRESQL */
-- "SERIAL" SERIA O MAIS PROXIMO
-- OUTRA OPÇÃO SERIA USAR "SEQUENCE"

-- SERIAL
CREATE TABLE CADASTRO(
IDCLIENTE SERIAL PRIMARY KEY,
NOME VARCHAR(50),
IDADE INT,
DATA DATE,
);